version: "3"
services:
  contact-hub:
    image: contact-hub
    ports:
      - "8080:8080"
    networks:
      - spring-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb

networks:
  spring-net: